# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
        
- stage: Stage
  displayName: Stage image
  jobs:
  - job: Stage
    displayName: Staged
    pool:
      vmImage: ubuntu-latest

- stage: Production
  displayName: Production image
  jobs:
  - job: Production
    displayName: Production
    pool:
      vmImage: ubuntu-latest

   
