trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
 
- stage: Dev
  displayName: Dev deployment
  jobs:
  - job: Dev
    displayName: Dev
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo "Add Dev deployment steps here"

- stage: Prod
  displayName: Prod deployment
  jobs:
  - job: Prod
    displayName: Prod
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureRmWebAppDeployment@5
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'NizamS(cdabd22b-60cc-42ad-8636-0358c8697be6)'
        appType: 'webApp'
        WebAppName: 'webapp2'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
