trigger:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: self
variables:
- name: tag
  value: '$(Build.BuildId)'
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
- stage: Dev
  displayName: Deploy to Dev
  jobs:
  - job: DevJob
    displayName: Dev Deployment
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      displayName: Placeholder for Dev steps
      inputs:
        script: echo "Dev deployment steps go here"
- stage: Prod
  displayName: Deploy to Prod
  jobs:
  - job: ProdJob
    displayName: Prod Deployment
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureAppServiceManage@0
      displayName: Start Azure App Service
      inputs:
        azureSubscription: 'NizamS(cdabd22b-60cc-42ad-8636-0358c8697be6)'
        action: 'Start Azure App Service'
        WebAppName: 'webapp2'
